[package]
name = "tracer"
version = "0.1.0"
authors = ["Karel <karel.peeters.leuven@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.0"
nalgebra = "0.19.0"
palette = "0.5.0"
rand = "0.7.3"
#rand_distr = "0.2.2"
#rayon = "1.3.0"
#itertools = "0.8.2"
#rand_xorshift = "0.2.0"
wavefront_obj = "7.0.0"

vulkano = "0.17"
vulkano-shaders = "0.17"